apiVersion: v1
kind: Namespace
metadata:
  name: static
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-deployment
  namespace: static
  labels:
    app: static
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static
  template:
    metadata:
      labels:
        app: static
    spec:
      containers:
      - name: static
        image: 306518615214.dkr.ecr.us-east-2.amazonaws.com/eks-staticwebsite:1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: static-svc
  namespace: static
spec:
  selector:
    app: static
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
#  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: static-ingress
  namespace: static
  annotations:
    kubernetes.io/ingress.class: static
spec:
 rules:
 - host: static.jyoismav.com
   http:
     paths:
     - path:  /
       backend:
         serviceName: static-svc
         servicePort: 80

